apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-bldx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-bldx
    app.kubernetes.io/part-of: cin4s-839-0024-app
  name: devfile-sample-bldx
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-bldx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-bldx
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/cin4s-839-0024-tenant/cin4s-839-0024-app/devfile-sample-bldx@sha256:86c93d333ef26b83ab3acb8fb86702717eab9505599ca4644ef844b874141a11
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
